language: c
sudo: required
before_install:
  - echo 'before install' && pwd && ls
  - mkdir -p ~/.ssh
  - openssl aes-256-cbc -K $encrypted_0f64f26238f6_key -iv $encrypted_0f64f26238f6_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa
  - cp ssh_config ~/.ssh/config
  - git config --global user.email "dvorak4tzx@qq.com"
  - git config --global user.name "TANG ZhiXiong"
install:
  - cd ~
  - wget https://github.com/jgm/pandoc/releases/download/1.17/pandoc-1.17-1-amd64.deb
  - sudo dpkg -i pandoc*.deb
  - wget https://github.com/whudoc/statics/raw/master/qrsync.tar.gz
  - tar xfz qrsync.tar.gz
  - chmod +x qrsync
  - sudo cp qrsync /bin
script:
  - cd ~/build/district10/blog;
  - make all sitemap
  - cat conf.json.in | sed -e "s/QiNiuAK/$QiNiuAK/" | sed -e "s/QiNiuSK/$QiNiuSK/" > conf.json; make qiniu; rm conf.json;
after_success:
  - echo "BLOG-PUBLISH";
  - cd ~/build/district10/blog;
  - cd publish; git clone https://github.com/district10/panorama-viewer.git panorama; cd panorama; rm -rf .git; cd ../..;
  - cd publish; git clone https://github.com/district10/texture-morpher.git tmorpher; cd tmorpher; rm -rf .git; cd ../..;
  - cd publish; git clone https://github.com/district10/notes.git /tmp/notes && (cd /tmp/notes && make); && mv /tmp/notes/publish notes; cd ..;
  - cd publish; rm **/*.md; cd ..;
  - cd publish; git init; git checkout -b gh-pages; echo 'blog.tangzhixiong.com' > CNAME; git add -A; git commit -m "AUTO PUBLISHED FROM DISTRICT10/BLOG"; git remote add origin git@github.com:district10/blog-publish.git; git push -u origin HEAD:gh-pages --force; cd ..;
  - echo "SOURCE-CODE-PUBLISH";
  - cd ~/build/district10/blog/publish;
  - rm -rf .git;
  - git init; git add -A; git commit -m "pushing to coding:coding-pages, lazy me @ `date`"
  - git remote add origin git@git.coding.net:dvorak4tzx/dvorak4tzx.git
  - git push -u origin HEAD:coding-pages --force
  - cd ..; rm -rf publish; git reset --hard HEAD;
  - rm -rf .git
  - git init; git add -A; git commit -m "pushing to coding:master, lazy me @ `date`"
  - git remote add origin git@git.coding.net:dvorak4tzx/dvorak4tzx.git
  - git push -u origin HEAD:master --force
